name: EventDeepDive
run-name: Run started by @${{ github.actor }} on ${{ ref }} for event ${{ event_name }} #Run ${{ run_number }} started by @${{ github.actor }} on ${{ ref }} for event ${{ event_name }}
on: 
  pull_request:
    type:
      - opened
    branches:
      - main
    tags:
      - v1.*
  workflow_dispatch:
  push:
    branches-ignore:
      - qa
      - main
    paths-ignore:
      - '.github/*'
    tags-ignore:
      - v2
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."